---
title: "About Me"
sidebar: false 
---

I was born in Trabzon in 2002 but grew up in Bursa. In 2020, I got into Hacettepe Electrical and Electronics Engineering and settled in Ankara. After my two-year undergraduate education, I transferred to the Industrial Engineering department, thinking it was more suitable for me.  
[Download My Resume](docs/OnurYucelResume.pdf)

# Education

-   B.S., Industrial Engineering, Hacettepe University, Turkey, 2023 - ongoing.

-   B.S., Electrical and Electronics Engineering, Hacettepe University, Turkey, 2020 - 2023 (Drop Off)

# Work Experience

Between September 2023 and August 2024, I worked as a game developer in our little game development crew, Gatto Games. Then we applied and got accepted to the Animasyon Teknolojileri ve Oyun Gelistirme Merkezi (ATOM) in ODTU TEKNOKENT. After 8 months of experience, we terminated the project.

## Employements

## Internships

# Projects

# Competencies

R, Quarto, Git, Python, C, C#

# Hobbies

Guitars, Football, Books and Movies
